server:
  port: 8085
spring:
  application:
    name: spring-boot-mvc-client
  security:
    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/msm_realm
      client:
        provider:
          msm_realm:
            issuer-uri: http://localhost:8080/realms/msm_realm
        registration:
          keycloak:
            provider: msm_realm
            client-id: msm
            client-secret: ethIYYocVE8fe1sR863sJswPtQjE4sBO
            authorization-grant-type: authorization_code
            scope: openid
#  logout-url: http://localhost:8080/realms/msm_realm/protocol/openid-connect/logout
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: redis-password

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true