server:
  port: 8085
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/msm_realm
keycloak:
  logout-url: http://localhost:8080/realms/msm_realm/protocol/openid-connect/logout
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: redis-password

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG